"""Add user education and work experience tables

Revision ID: 03e7981965cf
Revises: d45f34f1d010
Create Date: 2025-04-05 09:35:50.102469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e7981965cf'
down_revision = 'd45f34f1d010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.String(length=10), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posting_status', sa.String(length=100), nullable=True))
        batch_op.drop_column('job_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('posting_status')

    op.drop_table('work_experience')
    op.drop_table('user_education')
    # ### end Alembic commands ###
