"""Reset migration

Revision ID: 659203053cd3
Revises: 671eb281e5a0
Create Date: 2025-03-21 04:33:43.578690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659203053cd3'
down_revision = '671eb281e5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_users')
    # ### end Alembic commands ###
