"""Add user_auth_id to user_profiles

Revision ID: 75d82979786b
Revises: ae1ed4895086
Create Date: 2025-06-12 20:31:43.003820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d82979786b'
down_revision = 'ae1ed4895086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_auth_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_auth_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_auth_id')

    # ### end Alembic commands ###
