"""Add user_auth_id to JobPosting

Revision ID: 993a1d08fae9
Revises: 03e7981965cf
Create Date: 2025-04-06 21:24:46.862774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993a1d08fae9'
down_revision = '03e7981965cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_auth_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'auth_users', ['user_auth_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_auth_id')

    # ### end Alembic commands ###
